export const ADD_STICKY = 'ADD_STICKY';
export const DELETE_STICKY = 'DELETE_STICKY';
export const TOGGLE_STICKY_DELETE_STATUS = 'TOGGLE_STICKY_DELETE_STATUS';

export const ADD_TO_DO = 'ADD_TO_DO';
export const EDIT_TO_DO = 'EDIT_TO_DO';
export const DELETE_TO_DO = 'DELETE_TO_DO';
export const TOGGLE_TO_DO_STATUS = 'TOGGLE_TO_DO_STATUS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FETCH_FROM_STORAGE = 'FETCH_FROM_STORAGE';
export const CLEAR_FROM_STORAGE = 'CLEAR_FROM_STORAGE';
// export const UPADTE_IN_STORAGE = 'UPDATE_IN_STORAGE';